"""fit_anchor_explainer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1koFYTnjODZ_RgLalV-gEQfgBv2kbiKma

# Fit an Alibi Anchor Explainer for the Trained Classifier

This notebook loads `X_train.csv`, `y_train.csv`, and `xgb_model.joblib`, fits an
`alibi` `AnchorTabular` explainer against the training data using the model's
predictions, and exports the fitted explainer to disk as `anchor_explainer`.

**Note on the model file:** despite the filename `xgb_model.joblib`, unpickling it
shows it is actually a scikit-learn `LogisticRegression` model, not an XGBoost
model. The code below is written generically against the model's `.predict()`
method, so it works correctly regardless â€” but flagging this in case the wrong
file was uploaded.

We have to create and fit the anchor explainer here as pickling is leading to errors.
I think it's due to the model relying on information saved in memory which becomes
inaccaseable the second we actualy try to export it.
"""

from pathlib import Path
import os

import dill
import joblib
import numpy as np
import pandas as pd

from alibi.explainers import AnchorTabular

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

BASE_DIR = Path(__file__).resolve().parent
X_TRAIN_PATH = BASE_DIR / "X_train.csv"
Y_TRAIN_PATH = BASE_DIR / "y_train.csv"
MODEL_PATH = BASE_DIR / "logreg_model.joblib"
FEATURE_NAMES_PATH = BASE_DIR / "scope_binarizer_feature_names.pkl"
SAVE_PATH = BASE_DIR / "anchor_explainer.dill"

## Load data and model
X_train_raw = pd.read_csv(X_TRAIN_PATH)
y_train_raw = pd.read_csv(Y_TRAIN_PATH)

model = joblib.load(MODEL_PATH)

print(type(model))
print("X_train_raw shape:", X_train_raw.shape)
print("y_train_raw shape:", y_train_raw.shape)

"""## Clean up the feature matrix

The app's preprocessing module expects the feature vector to be ordered exactly
as the feature-names list in `scope_binarizer_feature_names.pkl`. We therefore:
1. drop the stray index-like `Unnamed: 0` column from the CSV export,
2. reindex the remaining columns to the exact feature-name order used by the
   app, and
3. enforce a binary 0/1 matrix before fitting the explainer.
"""

index_cols = [c for c in X_train_raw.columns if c.lower().startswith("unnamed")]
X_train_df = X_train_raw.drop(columns=index_cols)
feature_names = list(joblib.load(FEATURE_NAMES_PATH))
X_train_df = X_train_df.reindex(columns=feature_names, fill_value=0.0)

# Sanity checks: the training CSV should already be a binary one-hot matrix,
# just aligned to the app's preprocessing contract.
if X_train_df.columns.tolist() != feature_names:
    raise ValueError("Feature columns do not match the preprocessing feature-name order")

X_train_df = X_train_df.astype(float)
X_train = X_train_df.to_numpy(dtype=float)

if not np.isin(X_train, [0.0, 1.0]).all():
    raise ValueError("Training matrix contains values outside {0, 1}")

target_col = [c for c in y_train_raw.columns if not c.lower().startswith("unnamed")][0]
y_train = y_train_raw[target_col].to_numpy()

print("Feature matrix:", X_train.shape)
print("Number of features:", len(feature_names))
print("Target classes:", np.unique(y_train))

"""## Define the prediction function

`AnchorTabular` needs a callable that takes a 2D numpy array of raw feature rows
and returns the predicted class label for each row. We wrap the loaded model's
`.predict()` method directly.
"""

def predict_fn(x: np.ndarray) -> np.ndarray:
    return model.predict(x)

# Sanity check on a small slice of the training data.
sample_preds = predict_fn(X_train[:5])
print("Sample predictions:", sample_preds)
print("Sanity check accuracy on X_train:", (predict_fn(X_train) == y_train).mean())

"""## Fit the Anchor explainer

All 159 features here are binary (0/1) indicator columns (e.g. which Google API
scopes/services were used), so no categorical-name mapping is required â€”
`AnchorTabular` will treat them as numeric and discretize on the training
distribution as usual. We fit the explainer on `X_train`, which computes the
perturbation distribution used to generate anchors at explain-time.
"""

explainer = AnchorTabular(predict_fn, feature_names=feature_names, seed=RANDOM_STATE)
explainer.fit(X_train, disc_perc=(25, 50, 75))

explainer

"""## Quick smoke test

Generate one anchor explanation for the first training instance, just to confirm
the fitted explainer works end-to-end before saving it.
"""

explanation = explainer.explain(X_train[0], threshold=0.95)

print("Predicted class:", explanation.raw["prediction"])
print("Anchor:", explanation.anchor)
print("Precision: %.3f" % explanation.precision)
print("Coverage: %.3f" % explanation.coverage)

if SAVE_PATH.exists():
    SAVE_PATH.unlink()

saved_predictor = explainer.predictor
saved_mab = explainer.mab
explainer.predictor = None
explainer.mab = None

with open(SAVE_PATH, "wb") as f:
    dill.dump(explainer, f)

explainer.predictor = saved_predictor
explainer.mab = saved_mab

print(f"Saved explainer to {SAVE_PATH}")
print(SAVE_PATH.stat().st_size / 1e6, "MB")

with open(SAVE_PATH, "rb") as f:
    loaded_explainer = dill.load(f)

loaded_explainer.predictor = predict_fn

check_explanation = loaded_explainer.explain(X_train[0], threshold=0.95)
print("Anchor (reloaded explainer):", check_explanation.anchor)
print("Precision: %.3f" % check_explanation.precision)
print("Coverage: %.3f" % check_explanation.coverage)

# Anchors can differ between runs due to the random search — that's expected.
# What matters is that the reloaded explainer produces a valid, high-precision anchor.
assert check_explanation.precision >= 0.95, "Reloaded explainer failed to meet precision threshold"
print("Reloaded explainer produces valid anchors. Export verified.")